### PR TITLE
Error on unexisting field

### LINKED ISSUE #100: OGS doesn't validate that queried fields exist in the schema
The following query:
```graphql
query foo {
  somethingThatDoesntExistInQuery {
    ...
  }
}
```

returns
```json
{
  "data": {
    "somethingThatDoesntExistInQuery": null
  }
}
```

when it should probably result in a validation error (according to http://facebook.github.io/graphql/June2018/#sec-Executable-Definitions).

This happens at any level in the query, e.g. the following also doesn't produce a validation error:

```graphql
query {
  somethingThatExists {
    thisDoesntExist
  }
}
```

### PR DESCRIPTION
**Pull request by giltho**
Resolves #100 

Had to add the `subscriptionType` field to the `__Schema` type because the introspection query used contains it, but I kept the behavior it used to have (always returning `null` since it didn't exist).
That will create a very small merge conflict when merging #101

### CODE REVIEW

**Comment by anmonteiro** [comment]
@giltho I’m pretty sure my PR in #101 adds introspection support for subscriptions. What’s the motivation behind this change?

**Comment by giltho** [comment]
@anmonteiro yes yes it does, there will be a small merge conflict. But one of the test in the `schema` test suits verifies that the introspection query works correctly. However, with my pull request, since `subscriptionType` was not part of the the `__Schema` type, that test was failing (returning an error saying `"Cannot query 'subscriptionType' on type '__Schema'" which is the expected behavioyr when it is not defined.

That is why I defined it with a dummy behaviour until it is redefined in #101

File: graphql/src/graphql_schema.ml [hunk 1]
```diff
@@ -1057,19 +1066,20 @@ end
           lifted_value >>| (function
           | Ok (value, errors) ->
               Ok ((name, value), errors)
-          | Error (`Argument_error _) as err ->
-              err
+          | Error (`Argument_error _) as err -> err
+          | Error (`Validation_error _) as err -> err
```
Comment (rrosenzweig) [inline graphql/src/graphql_schema.ml]: These two patterns can be coalesced. For consistency, I'd also suggest `err` on it's own line like the other cases.

File: graphql/src/graphql_schema.ml [hunk 2]
```diff
@@ -1057,19 +1066,20 @@ end
...
           | Error (`Resolve_error err) as error ->
               match field.typ with
               | NonNullable _ ->
                   error
               | _ ->
                   Ok ((name, `Null), [err])
+
```
Comment (rrosenzweig) [inline graphql/src/graphql_schema.ml]: Superfluous blank line.

File: graphql/src/graphql_schema.ml [hunk 3]
```diff
@@ -1057,19 +1066,20 @@ end
...
                   error
               | _ ->
                   Ok ((name, `Null), [err])
+                
           )
       | Error err ->
           Io.error (`Argument_error err)
 
-  and resolve_fields : type ctx src. ctx execution_context -> ?execution_order:execution_order -> src -> (ctx, src) obj -> Graphql_parser.field list -> (Yojson.Basic.json * string list, [`Argument_error of string | `Resolve_error of string]) result Io.t =
+  and resolve_fields : type ctx src. ctx execution_context -> ?execution_order:execution_order -> src -> (ctx, src) obj -> Graphql_parser.field list -> (Yojson.Basic.json * string list, [`Validation_error of string | `Argument_error of string | `Resolve_error of string ]) result Io.t =
```
Comment (rrosenzweig) [inline graphql/src/graphql_schema.ml]: There's an additional space before the right bracket.

File: graphql/src/graphql_schema.ml [hunk 4]
```diff
@@ -1079,7 +1089,9 @@ end
           | Some field ->
               resolve_field ctx src query_field field
           | None ->
-              Io.ok ((alias_or_name query_field, `Null), [])
+              let error_message = Printf.sprintf "Cannot query field '%s' on type '%s'" query_field.name obj.name in
```
Comment (rrosenzweig) [inline graphql/src/graphql_schema.ml]: To align with the wording of the spec, I'd suggest `"Field '%s' is not defined on type '%s'"`.

File: graphql/test/schema_test.ml [hunk 5]
```diff
@@ -106,6 +106,26 @@ let suite = [
...
+  ("unexisting fields should be caught", `Quick, fun () ->
+    let query = "{ users { id foo } }" in
+    test_query query (`Assoc [
+      "errors", `List [
+        `Assoc [
+          "message", `String "Cannot query field 'foo' on type 'user'"
+        ]
+      ]
+    ])
+  );
```
Comment (rrosenzweig) [inline graphql/test/schema_test.ml]: Naming-wise, I'd suggest:

- `"undefined field on query root"`
- `"undefined field on object type"`

File: graphql/src/graphql_schema.ml (hunk 1 above)
Comment (rrosenzweig) [reply graphql/src/graphql_schema.ml]: This seems to work for me:

```ocaml
          | Error (`Argument_error _)
          | Error (`Validation_error _) as err ->
              err
```

Comment (giltho) [reply graphql/src/graphql_schema.ml]: Oh turns out I didn't know the syntax correctly
you don't have to add `as err` on both lines
I'll fix that now

File: graphql/src/graphql_schema.ml [hunk 6]
```diff
@@ -1079,7 +1089,9 @@ end
           | Some field ->
               resolve_field ctx src query_field field
           | None ->
-              Io.ok ((alias_or_name query_field, `Null), [])
+              let error_message = Printf.sprintf "Field '%s' is not defined on type '%s'" query_field.name obj.name in
+              Io.error (`Validation_error error_message)
+
```
Comment (rrosenzweig) [inline graphql/src/graphql_schema.ml]: Superfluous blank line.

**Comment by giltho** [comment]
Done 😄

**Comment by rrosenzweig** [comment]
Thanks for your contribution @giltho! 👍
